apiVersion: app.o0w0o.cn/v1
kind: MicroService
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: gateway-sample
spec:
  loadBalance:
    service:
      name: gateway-sample
      spec:
        ports:
        - protocol: TCP
          port: 80
          targetPort: 80
    ingress:
      name: gateway-sample
      spec:
        rules:
        - host: foo.o0w0o.cn
          http:
            paths:
              - path: /bar
                backend:
                  serviceName: gateway-sample
                  servicePort: 80
  versions:
    - name: v1
      template:
        replicas: 1
        selector:
          matchLabels:
            app: nginx-v1
        template:
          metadata:
            labels:
              app: nginx-v1
          spec:
            containers:
            - image: nginx
              name: nginx
      serviceName: gateway-sample-v1
    - name: v2
      canary:
        weight: 10
      template:
        replicas: 1
        selector:
          matchLabels:
            app: nginx-v2
        template:
          metadata:
            labels:
              app: nginx-v2
          spec:
            containers:
            - image: nginx
              name: nginx
      serviceName: gateway-sample-v2
  currentVersionName: v1
